---
# tasks file for docker
- name: 安装必要的系统工具
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present
- name: 添加docker源
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
- name: 安装docker
  yum:
    name:
      - containerd.io-1.2.13
      - docker-ce-19.03.11
      - docker-ce-cli-19.03.11
    state: present
- name: 创建docker目录
  file:
    path: /etc/docker
    state: directory
    mode: 0755
- name: 从模板复制配置文件
  template: src=daemon.json.j2 dest=/etc/docker/daemon.json
- name: 重新加载配置文件
  command: systemctl daemon-reload
- name: 启动docker
  command: systemctl start docker
- name: docker开机启动
  command: systemctl enable docker
