---
# tasks file for ipvs
- name: 安装ipvs所需软件
  yum:
    name:
      - ipvsadm
      - ipset
      - sysstat
      - conntrack
      - libseccomp
    state: present
- name: 复制ipvs模块加载文件
  template: src=ipvs.conf.j2 dest=/etc/modules-load.d/ipvs.conf
- name: 复制内核优化文件
  template: src=k8s.conf.j2 dest=/etc/sysctl.d/k8s.conf
- name: 重新加载配置
  command: systemctl enable --now systemd-modules-load.service
- name: 重新加载配置
  command: sysctl --system

