---
# tasks file for k8s
- name: 添加k8s yum仓库
  template: src=kubernetes.repo.j2 dest=/etc/yum.repos.d/kubernetes.repo
- name: 安装k8s
  yum:
    name:
      - kubelet-1.20.4-0
      - kubeadm-1.20.4-0
      - kubectl-1.20.4-0
    state: present
- name: 复制并替换kubeadm
  copy:
    src: "kubeadm"
    dest: "/usr/bin/kubeadm"
- name: 启动kubelet
  command: systemctl enable --now kubelet
- name: 配置admin环境变量
  raw: "echo export KUBECONFIG=/etc/kubernetes/admin.conf >> /root/.bash_profile"
