---
# tasks file for common
- name: 修改主机名
  raw: "echo {{hostname|quote}} > /etc/hostname"
- name: 修改hosts
  raw: "echo {{inventory_hostname}} {{hostname}} >> /etc/hosts"
- name: yum安装基本软件
  yum:
    name: ['vim', 'wget']
    state: installed
